apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    email: example@hosteur.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: example-issuer-account-key
    solvers:
    - dns01:
        webhook:
          groupName: acme.hosteur.com
          solverName: hosteur-dns-solver
          config:
            apiEndpoint: "https://api.hosteur.com"
            apiClientIDSecretRef:
              Name: "api.hosteur.com-credentials"
              Key:  "ClientID"
            apiKeySecretRef:
              Name: "api.hosteur.com-credentials"
              Key:  "K_KEY"
---
apiVersion: v1
kind: Secret
metadata:
  name: api.hosteur.com-credentials
  namespace: cert-manager
type: Opaque
data:
  ClientID: "<base64 api ClientID>"
  K_KEY: "<base64 api key>"